SYNOPSIS
        void throw(mixed arg)

BESCHREIBUNG
        Bricht die Programmverarbeitung ab. Wenn die Verarbeitung mit catch()
        gestartet wurde, gibt dieses catch() <arg> als Fehlermeldung aus.

        Der Aufruf von throw() ohne vorheriges catch() macht keinen Sinn und
        erzeugt einen "throw without catch" Fehler.

BEISPIELE
        catch(throw("Verarbeitung abgebrochen!"));
        Das macht nichts als "Verarbeitung abgebrochen!" auszugeben.

SIEHE AUCH
        catch(E), raise_error(E)
